# Generated by Django 5.1.6 on 2025-04-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
