# Generated by Django 5.1.6 on 2025-04-01 12:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0002_alter_article_contenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sectionarticle',
            name='content',
        ),
        migrations.AddField(
            model_name='rapport',
            name='contenu',
            field=ckeditor.fields.RichTextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionarticle',
            name='contenu',
            field=ckeditor.fields.RichTextField(default='Hello'),
            preserve_default=False,
        ),
    ]
