# Generated by Django 5.1.6 on 2025-06-06 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0006_gallerie_gallerieimage_delete_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerie',
            options={'ordering': ['-id'], 'verbose_name_plural': 'GALERIES'},
        ),
        migrations.AlterModelOptions(
            name='gallerieimage',
            options={'ordering': ['-id'], 'verbose_name_plural': 'IMAGES DE LA GALERIE'},
        ),
        migrations.AlterField(
            model_name='rapport',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
