# Generated by Django 5.1.6 on 2025-07-11 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0007_alter_gallerie_options_alter_gallerieimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('profil_recherche', models.TextField()),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('INTERIM', 'Intérim')], max_length=20)),
                ('lieu', models.CharField(max_length=255)),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('lien_postulation', models.URLField(blank=True, null=True, verbose_name='Lien vers le formulaire de candidature')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-date_publication'],
            },
        ),
    ]
