# Generated by Django 5.1.6 on 2025-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0008_joboffer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-date_publication'], 'verbose_name_plural': "OFFRES D'EMPLOI"},
        ),
        migrations.AddField(
            model_name='joboffer',
            name='counter_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
