# Generated by Django 5.1.6 on 2025-07-12 15:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0010_joboffer_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='profil_recherche',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
