# Generated by Django 5.1.6 on 2025-08-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0011_alter_joboffer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='type_rapport',
            field=models.CharField(choices=[('rapport', 'Rapport'), ('activite', 'Activité')], default='rapport', max_length=10),
        ),
    ]
