# Generated by Django 5.1.6 on 2025-08-03 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0012_rapport_type_rapport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRapportActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='rapports/')),
                ('link_video', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnhelp_api.rapport')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('rapport', 'order')},
            },
        ),
    ]
