# Generated by Django 5.1.6 on 2025-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0013_mediarapportactivite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediarapportactivite',
            options={'ordering': ['order'], 'verbose_name_plural': 'MEDIA RAPPORT ACTIVITE'},
        ),
        migrations.AddField(
            model_name='mediarapportactivite',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
