# Generated by Django 5.1.6 on 2025-09-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnhelp_api', '0014_alter_mediarapportactivite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='partenaires',
            field=models.ManyToManyField(blank=True, related_name='rapports_partenaires', to='wnhelp_api.partenaires'),
        ),
    ]
